---
- name: "({{ role_name }}) source .bash_profile"
  shell:
  become: yes
  become_method: su
  become_user: oracle
  #become_flags: "-s /bin/sh"
  args:
    cmd: source /home/oracle/.bash_profile
    #chdir:
    # when filename already exists, this step *won't* be run.
    #creates:

    # when filename already exists, this step *will* be run.
    #remove:
