---
- name: <r_mount_points_t_common> create mount points directory
  file:
    path: "{{ item.point }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: "0775"
  loop: "{{ mount_map | dict2items }}"

- name: <r_mount_points_t_common> mount up devices
  mount:
    path: "{{ item.point }}"
    src: "LABEL={{ item.volume }}"
    fstype: xfs
    #opts:

    # If `mounted', the device will be actively mounted and
    # appropriately configured in `fstab'. If the mount point is not
    # present, the mount point will be created.
    #
    # If `unmounted', the device will be unmounted without changing `fstab'.
    #
    # `present' only specifies that the device is to be configured
    # in `fstab' and does not trigger or require a mount.
    #
    # `absent' specifies that the device mount's entry will be
    # removed from `fstab' and will also unmount the device and
    # remove the mount point.
    #
    # `remounted' specifies that the device will be remounted for
    # when you want to force a refresh on the mount itself (added in
    # 2.9). This will always return changed=true.
    #
    # Choices: absent, mounted, present, unmounted, remounted
    state: mounted
  loop: "{{ mount_map | dict2items }}"
