---
# defaults file for resource_limits

# FROM TASK: "<r_resource_limits_t_common> template a file to /etc/security/limits.d/{{ limits_conf_file }}"
limits_conf_file: 80-oracle.conf
# References:
# - [Checking Resource Limits for Oracle Software Installation Users](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ladbi/checking-resource-limits-for-oracle-software-installation-users.html#GUID-293874BD-8069-470F-BEBF-A77C06618D5A)
#
# at least 90 percent of the current RAM when HugePages memory is enabled and at least 3145728 KB (3 GB) when HugePages memory is disabled
mem_total_kb: "{{ (ansible_facts['memtotal_mb'])*1024 }}"
memlock_limit: "{{ ((mem_total_kb | float)*0.9) | int }}"
