---
- name: <r_response_files_t_common> template a file to /home/oracle/database/db_inst.rsp
  template:
    src: db_inst.rsp.j2
    dest: /home/oracle/database/db_inst.rsp
    owner: oracle
    group: oinstall
    mode: "0775"
    #validate:
    #backup: yes
