---
- name: "<r_response_files_t_prepare_netca> copy a file to {{ oracle_home }}/"
  copy:
    # if path ends with "/", only inside contents of that
    # directory are copied to destination.
    # if it does not end with "/", the directory itself
    # with all contents is copied.
    src: netca.rsp
    dest: "{{ oracle_home }}/"
    owner: oracle
    group: oinstall
    mode: "0644"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:
