---
- name: "<r_response_files_t_prepare_dbca> copy a file to {{ oracle_home }}/"
  copy:
    # if path ends with "/", only inside contents of that
    # directory are copied to destination.
    # if it does not end with "/", the directory itself
    # with all contents is copied.
    src: General_Purpose.dbc
    dest: "{{ oracle_home }}/"
    owner: oracle
    group: oinstall
    mode: "0775"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:

- name: "<r_response_files_t_prepare_dbca> template a file to {{ oracle_home }}/dbca.rsp"
  template:
    src: dbca.rsp.j2
    dest: "{{ oracle_home }}/dbca.rsp"
    owner: oracle
    group: oinstall
    mode: "0775"
    #validate:
    #backup: yes
