---
- name: <pr_r_security_t_common> disable selinux
  selinux:
    state: disabled

- name: <pr_r_security_t_common> stop and disable service firewalld
  systemd:
    name: firewalld
    # Choices: reloaded, restarted, started, stopped
    state: stopped
    enabled: no
    #daemon_reload: yes
