---
- name: <r_oracle_dirs_t_common> create oracle required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: "0775"
  loop:
    - "{{ oracle_base }}"
    - "{{ oracle_inventory }}"
    - "{{ oracle_home }}"
