---
- name: "<r_resource_limits_t_common> template a file to /etc/security/limits.d/{{ limits_conf_file }}"
  template:
    src: "{{ limits_conf_file  }}.j2"
    dest: "/etc/security/limits.d/{{ limits_conf_file }}"
    owner: root
    group: root
    mode: "0644"
    #validate:
    #backup: yes
